import { SessionProvider } from "next-auth/react";
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
